### ISSUE TITLE
smallband (squeezed) as a selectable attribute

### ISSUE THREAD

**Issue by SvenMazet** [myTselection/telenet_telemeter#18]
I've been trying to set up a smallband indicator in a similar screen like your example, but I can't seem to get it to work ... I know it's in the attributes of the sensor, but can't seem to use it in a card.

![image](https://user-images.githubusercontent.com/68681773/224722626-cf070dca-deac-4015-be49-6ea7a62b00d9.png)

Perhaps this could be a selectable item for sensor.telenet_telemeter?

**Comment by myTselection** [comment]
aha, I didn't know this 'squeezed' element was used to denote this. I can add it as a direct attribute on the sensor.
For now, it's only available as a deeply nested attribute within telemeter_json
so for now you could try: `{{state_attr('sensor.telenet_telemeter','telemeter_json')['internetusage'][0]['availableperiods'][0]['usages'][0]['squeezed']}}`

**Comment by SvenMazet** [comment]
That did the trick!
![afbeelding](https://user-images.githubusercontent.com/68681773/225261740-2e624b14-50f7-4ae0-bc3d-278b42258c34.png)
Thank you for your help, and looking forward to continued developement.

Kind regards,
Sven

**Comment by myTselection** [comment]
I forgot to mention in here a new release was release yesterday [r0.8.0](https://github.com/myTselection/telenet_telemeter/releases/tag/0.8.0), which has this extra attribute as a direct attribute on the `telenet_telemeter` and `telenet_telemeter_peak` sensors, so they are much easier to reach.
