### ISSUE TITLE
Still issue with values for business plan

### ISSUE THREAD

**Issue by wokkeltje13** [myTselection/telenet_telemeter#25]
Still nu visual difference in the MyTelenet GUI, so probably not on the V2 API
Attached the complete config as seen in HA so you maybe can find why this is not working.
[Telenet.txt](https://github.com/myTselection/telenet_telemeter/files/11128746/Telenet.txt)

I also see some errors:

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/telenet_telemeter/sensor.py:287
Integration: Telenet Telemeter (documentation, issues)
First occurred: 30 March 2023 at 22:34:11 (4204 occurrences)
Last logged: 09:35:46

Update for sensor.telenet_telemeter_internet_u559057 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/telenet_telemeter/sensor.py", line 287, in async_update
    for elem in self._data._product_details.get('product').get('characteristics').get('elementarycharacteristics'):
TypeError: 'NoneType' object is not iterable

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/telenet_telemeter/sensor.py:547
Integration: Telenet Telemeter (documentation, issues)
First occurred: 30 March 2023 at 22:34:10 (4204 occurrences)
Last logged: 09:35:46

Update for sensor.telenet_telemeter_peak_u559057 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/telenet_telemeter/sensor.py", line 547, in async_update
    for elem in self._data._product_details.get('product').get('characteristics').get('elementarycharacteristics'):
TypeError: 'NoneType' object is not iterable

**Comment by myTselection** [comment]
thx, will take a look into it

**Comment by myTselection** [comment]
I've checked your product details. Yet, I don't see any option yet to retrieve your max volume. I need that to know the used percentage.
Could you share a screenshot of your official Telenet telemeter? What is Telenet showing as max volume?

**Comment by wokkeltje13** [comment]
There is no limit
![image](https://user-images.githubusercontent.com/57153640/229344580-b0db6cf3-7c9d-4076-8b4c-b34bf69a2309.png)

I am not interested in the % used, but would like to see the daily usage to see if there is something exceptional going over the line.

**Comment by myTselection** [comment]
Thanks for your input, I've created a new releast 0.9.5, I hope it will solve your case.

**Comment by wokkeltje13** [comment]
as far as I can see everything is working, tnx for your work.

I am just wondering what the following 2 values mean
included_volume and total_volume

attribution: Telenet Telemeter
last update: '2023-04-02T18:14:05.3+02:00'
used_percentage: 0
included_volume: 10485759975882752
extended_volume: 0
total_volume: 9999999977
wifree_usage: 0
includedvolume_usage: 0
extendedvolume_usage: 0
peak_usage: 7547804
offpeak_usage: 18644152
sequeezed: false
period_start: '2023-04-02T00:00:00+02:00'
period_end: '2023-05-01T00:00:00+02:00'
period_days_left: 28.2
period_used_percentage: 2.7
product: K2SLim
download_speed: 300 Mbps
upload_speed: 30 Mbps

**Comment by wokkeltje13** [comment]
Still 2 errors,


Logger: homeassistant.config_entries
Source: config_entries.py:1419
First occurred: 19:02:22 (1 occurrences)
Last logged: 19:02:22

Error calling entry remove callback Telenet Telemeter for telenet_telemeter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 579, in async_remove
    await component.async_remove_entry(hass, self)
  File "/config/custom_components/telenet_telemeter/__init__.py", line 89, in async_remove_entry
    await hass.config_entries.async_forward_entry_unload(config_entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1419, in async_forward_entry_unload
    if domain not in self.hass.config.components:
TypeError: unhashable type: 'list'


This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/telenet_telemeter/sensor.py:567
Integration: Telenet Telemeter (documentation, issues)
First occurred: 15:29:03 (473 occurrences)
Last logged: 19:26:11

Update for sensor.telenet_telemeter_peak_u559057 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/telenet_telemeter/sensor.py", line 567, in async_update
    for elem in self._data._product_details.get('product').get('characteristics').get('elementarycharacteristics'):
TypeError: 'NoneType' object is not iterable
