### ISSUE TITLE
Attribute fields not filled in

### ISSUE THREAD

**Issue by TASSDevon** [myTselection/telenet_telemeter#26]
I just installed this plugin, somehow the json data is not converted into the attribute fields, tried reloading the integration but no luck:

<img width="564" alt="Screenshot 2023-04-01 at 13 07 17" src="https://user-images.githubusercontent.com/6917072/229285239-80b0280d-373c-4f35-99cb-b175c325f0d3.png">

The peak entity does seem to have its fields correct:
<img width="550" alt="Screenshot 2023-04-01 at 13 09 06" src="https://user-images.githubusercontent.com/6917072/229285277-26eda1c0-b8b0-4c4a-a909-a7fd933f1a7a.png">

Any ideas?

EDIT:
Should've checked the logs sooner:

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/telenet_telemeter/sensor.py:287
Integration: Telenet Telemeter (documentation, issues)
First occurred: 11:43:32 (175 occurrences)
Last logged: 13:11:00

Update for sensor.telenet_telemeter_internet_<SNIP> fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/telenet_telemeter/sensor.py", line 287, in async_update
    for elem in self._data._product_details.get('product').get('characteristics').get('elementarycharacteristics'):
TypeError: 'NoneType' object is not iterable

```

**Comment by myTselection** [comment]
Thanks for your input, I've created a new releast 0.9.5, I hope it will solve your case.

**Comment by TASSDevon** [comment]
Confirmed ;-)

<img width="378" alt="Screenshot 2023-04-02 at 19 01 25" src="https://user-images.githubusercontent.com/6917072/229367621-510824be-5943-425f-94bd-00bb086e2ff8.png">
