### ISSUE TITLE
Enhancement - higher resolution integration image

### ISSUE THREAD

**Issue by XalaTheShepard** [myTselection/telenet_telemeter#30]
Dear myTselection,

I have noticed that the image of your integration has a rather low resolution. 
If possible, could you provide it with an image with a higher resolution? 

Thanks in advance. 

Kind regards, 

Robin

**Comment by myTselection** [comment]
hi, which image do you mean exaclty? not fully clear to me

**Comment by XalaTheShepard** [comment]
![image](https://github.com/myTselection/telenet_telemeter/assets/69390987/2e54dfcb-d56a-44e9-831a-3ffef87548e0)

Dear myTselection, 

I mentioned the image of the Telenet Telemeter on the integration page. 
It seems like it was snipped from the website of Telenet or somewhere else, as it has a low resolution and it is a bit odd. 
Only a minor enhancement, but looks nicer in the integrations page. 

Thanks in advance. 

Kind regards, 

Robin

**Comment by myTselection** [comment]
all HA integration images have the same mandatory resolution (256x256). The transparancy at the borders was maybe not fully optimal, but only visible in dark mode.
