### ISSUE TITLE
The consumption display for all mobiles is always set to unknown

### ISSUE THREAD

**Issue by Mulle00** [myTselection/telenet_telemeter#31]
The consumption display for all mobiles is always set to unknown. On the Telenet website, however, these are correct.
It has never worked with since I have been using the integration.

I have a One subscription with 2 unlimited sims + 1 data sim.

Did I configure something wrong?

Thanks in advance for the help

![Schermafbeelding 2023-08-10 210751](https://github.com/myTselection/telenet_telemeter/assets/25512372/1da16414-b50f-4d1f-8700-c021340882d5)

**Comment by myTselection** [comment]
hi, is still an issue?
could you share the full details of the 'mobile json' attribute?
could you also enable debug logging in the integration and share the relevant logs? see instructions https://github.com/myTselection/telenet_telemeter#technical-pointers
migtht be the handling is different for specific subscription types...
