### ISSUE TITLE
End Date time is wrong

### ISSUE THREAD

**Issue by hastaboera** [myTselection/telenet_telemeter#35]
Hi,

The end date time is the last day @ 00:00:00 instead of 23:59:59 and counts for that reason not correct.

If i need to provider more info please let me know. (totally new with this)

Thanks!

**Comment by myTselection** [comment]
hi, thanks for your feedback, but it's not fully clear what you mean.

Could this be related to mobile sensor, the "period_end" attribute? This is the data coming from Telenet "nextbillingdate". Maybe I can just substract one day? 

Could you share an example? I don't have a mobile subscription myself so not fully clear what's shown currently..

**Comment by hastaboera** [comment]
Hi,

yes, period_end is the one. To me it seems the V2 is adding a time which is 00:00:00 (beginning of the day) but should have 23:59:59 otherwise you lose a whole day or you should add a day so my period_end is 22-12-2023
![afbeelding](https://github.com/myTselection/telenet_telemeter/assets/140069945/ee97e3ff-ad04-4570-9692-8e40e2b46d29)

My next period_start will be 22-12-2023 00:00:00
this period_end is                 21-12-2023 00:00:00 (there is a whole day between period_end and next period_start
proposal for period_end      21-12-2023 23:59:59

i also had to hash out a wifree line @ line 358 otherwise the integration had issues parsing the data.
![afbeelding](https://github.com/myTselection/telenet_telemeter/assets/140069945/9aa4fcf3-0a30-4a34-bfa9-3796df188110)
Telenet has stopped that service
[https://www2.telenet.be/residential/nl/klantenservice/internet/meer-over-je-internet/stopzetting-telenet-wi-free](url)

If needed i create a new issue for that, just let me know :)

**Comment by myTselection** [comment]
could you check if R1.5.2 is fixing your needs?

**Comment by hastaboera** [comment]
Hi, looks OK! thanks!
