### ISSUE TITLE
no sensor created - sensor.telenet_telemeter_internet - Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Roeli1996** [myTselection/telenet_telemeter#39]
Good afternoon

I just added the integration via HACS.
Both internet and mobile are checked in the configuration. The connection was successful. However, no sensor is created "sensor.telenet_telemeter_internet_".

I get the following information in the log files:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
   File "/config/custom_components/telenet_telemeter/sensor.py", line 118, in async_setup_entry
     await dry_setup(hass, config, async_add_devices)
   File "/config/custom_components/telenet_telemeter/sensor.py", line 51, in dry_setup
     await data_internet._forced_update()
   File "/config/custom_components/telenet_telemeter/sensor.py", line 153, in _forced_update
     await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
     result = self.fn(*self.args, **self.kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/telenet_telemeter/sensor.py", line 153, in <lambda>
     await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^
   File "/config/custom_components/telenet_telemeter/utils.py", line 97, in login
     self.callTelenet("https://api.prd.telenet.be/ocapi/oauth/userdetails","login")
   File "/config/custom_components/telenet_telemeter/utils.py", line 80, in callTelenet
     assert response.status_code == expectedStatusCode
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Thanks in advance!

**Comment by myTselection** [comment]
Hi, this seems to be caused by a wrong username and/or password set in the Telenet Telemeter addon. Or maybe some very special characters are used in the password which are might not be well supported. could you try to remove the device and add again and if still issues set a new password via the Telenet website. Please also make sure to upgrade to the latest version of this integration (1.5.4) and reboot HA before adding the device.

**Comment by Roeli1996** [comment]
Thank you! After changing the password, I got everything as expected.
Remarkable: I had to change the password via 'forgotten password'. Changing after logging in to my telenet was not possible. Unprecedented error.

Problem solved now. Thank you!
