### ISSUE TITLE
API change Telenet - Broke even their own applications

### ISSUE THREAD

**Issue by Vandewaetere** [myTselection/telenet_telemeter#42]
Hi,

I notice that the Telenet App is showing 0GB both web application and App.

![image](https://github.com/myTselection/telenet_telemeter/assets/2471011/23415ce6-2a3a-447c-b6fc-bd68ead115ce)

Integration is also showing 0GB, I see that the json structure has changed.
Did this also change for anyone else? @myTselection 

Funny how we can fix this ourselves even before Telenet fixes their own applications.
Did a temporary test by simply doing:

![image](https://github.com/myTselection/telenet_telemeter/assets/2471011/e4a9344b-e668-4eeb-9c42-66ed6888a974)

Not sure if I should wait until their own apps work again to be sure that the API is not in a state of constant flux ;-)

**Comment by myTselection** [comment]
thx for the heads up. Will take a look into it in coming days to see if I get similar results...

**Comment by Vandewaetere** [comment]
Looks like it is all working again. Telemeter Page does look updated now on My Telenet. Closing issue.
