### ISSUE TITLE
Incorrect consumption value

### ISSUE THREAD

**Issue by Pitsaer** [myTselection/telenet_telemeter#46]
Hello, In H.A I get a value ;

**Total used: 6.81% (204GB of 3000GB) 
13 days remaining (2796GB) 
Period 05-03-2024 - 05-04-2024 
All-Internet: 300 Mbps/20 Mbps (Peak 6.81, 300 Mbps)
Laatste update: 22-03-2024 09:08**

But if I look on the Telenet site I am at **502.02 GB consumed Mar 05 - Apr 04 Current billing period (Last updateMarch 21 23:39).**

Any ideas where the trouble comes from? 
Thanks

**Comment by myTselection** [comment]
In Telenet, you may need to enable the option 'Show off-peak hours' (Toon daluren) to see the same details as shown in HA. 
Only the usage during peak hours is to be considered/limited for All-Internet subscription. So only that part is considered to calculate the percentage.
So to get to the 502.02GB you should sum up the `peak_usage` and `offpeak_usage`. When using the [apex chart example](https://github.com/myTselection/telenet_telemeter?tab=readme-ov-file#apex-chart-card), this should become clearly visible too.

**Comment by Pitsaer** [comment]
Good point, thanks for the info, I didn't know that only peak hours were counted for the subscription. 
:-)
