### ISSUE TITLE
Telemeter give me 0%

### ISSUE THREAD

**Issue by Novan007** [myTselection/telenet_telemeter#47]
Hello I al a beginner. I have the latest telemeter but give me 0% it must 32%. The mobile meter works fijne. Can someone help me?
![c231a2185c0ce93deb720c6b0b5692a26f3933a2](https://github.com/myTselection/telenet_telemeter/assets/169708981/f5c3a149-7148-4421-8b66-b54479c406bc)

**Comment by Novan007** [comment]
Are there people still working on these hacs or is it doomed?

**Comment by myTselection** [comment]
I'm actively maintaining it, but I don't have these issues, it's still showing up correctly for me.

Please note the main internet sensor is only showing the peak usage. So if comparing with the stats shown by the Telenet app, you should make sure to first enable the details stats (indicating peak and offpeak usage).

**Comment by Novan007** [comment]
Thank you but i think is the telemeter of Telenet that is not working see picture:
![Naamloos-1](https://github.com/myTselection/telenet_telemeter/assets/169708981/d7ba6979-4c2a-4509-8b3f-3e6f0cbc3085)
![Naamloos-2](https://github.com/myTselection/telenet_telemeter/assets/169708981/a76d946e-d438-478d-97c0-2b8328771133)
Everthing work fine only the usage of the internet is 0.

**Comment by Novan007** [comment]
OK i now the problem i have wigo home 6GB and there is no indicating peak and offpeak usage in the telemeter only the volume usage. So I have contacted Telenet and the technicien are working on it.
