### ISSUE TITLE
Remember previous value after reboot

### ISSUE THREAD

**Issue by hastaboera** [myTselection/telenet_telemeter#49]
After reboot of HA the sensor always goes to zero for a short period.
Could the sensor go to previous value after reboot?

![afbeelding](https://github.com/user-attachments/assets/5b300897-8a32-442d-80fa-5e3514c72973)

**Comment by myTselection** [comment]
I might default it to 'unavailable' instead of 0, which will have less impact on your graph.

**Comment by myTselection** [comment]
hopefully better as of R1.6.2.
