### ISSUE TITLE
Fresh install telenetmeter

### ISSUE THREAD

**Issue by Tankyspanky** [myTselection/telenet_telemeter#51]
I have installed telenetmeter but all that comes up is one identity : Telenet Telemeter Wifi
There are no other items like my Internet or the 2 mobile phones?

**Comment by myTselection** [comment]
ok i will check again. Can you confirm you are on latest release (currently R1.8.0)?

**Comment by mantaalex** [comment]
![image](https://github.com/user-attachments/assets/61c42959-5ca5-49db-8352-2d49fb284519)
i first had only the wifi working the others where not available
i reinstalled the account now only the wifi

**Comment by myTselection** [comment]
thx for reporting! I found some family member with a bundle subscription so I could test and fix these flows now myself, 
I hope it's now all fixed as of R1.8.1.

**Comment by Tankyspanky** [comment]
Super, Gefixed :)
Nu moet ik nog even zoeken hoe ik de mobiele nummers apart te zien krijg erbij :) 

![image](https://github.com/user-attachments/assets/5535620d-fee4-4906-b07f-13a3922d5ec5)
