### ISSUE TITLE
Add support for mobile subscriptions usage

### ISSUE THREAD

**Issue by myTselection** [myTselection/telenet_telemeter#6]

**Comment by myTselection** [comment]
I've added inital code to support mobile usage, would need the data of 'sensor.telenet_telemeter_mobile' attribute 'mobile_json' of some user in order to know which data can be retrieved.
Would create a separate sensor for each mobile number in the data set later on.

**Comment by myTselection** [comment]
dear @Nasimovy, could you test latest release and share mobile_json results witht personal data removed?

**Comment by Nasimovy** [comment]
hello im trying to get the logs for you but i have no luck 

2023-01-17 21:47:59.210 DEBUG (SyncWorker_0) [custom_components.telenet_telemeter.utils] telemeter result status code: 400
2023-01-17 21:47:59.210 DEBUG (SyncWorker_0) [custom_components.telenet_telemeter.utils] telemeter result {"code":"OCAPI-ERR-032","cause":"ODATA is in maintenance mode","correlationId":"63c608b2-f479-4e9a-9c3a-f8fa5121b00e"}
2023-01-17 21:47:59.212 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up telenet_telemeter platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 85, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 52, in dry_setup
    await data_internet._init()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 123, in _init
    self._telemeter = await self._hass.async_add_executor_job(lambda: self._session.telemeter())
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 123, in <lambda>
    self._telemeter = await self._hass.async_add_executor_job(lambda: self._session.telemeter())
  File "/config/custom_components/telenet_telemeter/utils.py", line 103, in telemeter
    assert response.status_code == 200
AssertionError

odata is in maintenance mode?

**Comment by myTselection** [comment]
I notice the official app of Telenet is also offline, so it's only related to their environment. It should be back online on 18/01 8u.

**Comment by Nasimovy** [comment]
ah okay, i will check the logs and report back tomorrow

**Comment by Nasimovy** [comment]
here is the log.

the first sim card is a full sim so data,calling,.......
the second sim is a data only sim
they share the same data pool of 300GB



mobileusage:
- label: O1
specurl: https://api.prd.telenet.be/omapi/public/product/42797
identifier: O1_46172164
nextbillingdate: '2023-01-26T00:00:00.0+01:00'
lastupdated: '2023-01-18T09:10:24.0+01:00'
address:
street: 
postalcode: ''
municipality: 
country: 
housenr: ''
addressid: 
unassigned:
mobilesubscriptions: []
profiles:
- pid: ''
role: manager
firstname: 
lastname: 
nickname: 
paused: false
mobilesubscriptions:
- mobile: ''
sim: ''
pin: ''
puk: ''
activationstate: active
included:
data:
startunits: 300
start: '300'
remainingunits: 277.69
remaining: 277,69
usedunits: 22.31
used: 22,31
usedpercentage: 7
unittype: GB
unlimited: true
text:
startunits: 30000
remainingunits: 29990
usedunits: 10
usedpercentage: 0
unittype: number
unlimited: true
scaledusedpercentage: 1
voice:
startunits: 180000
remainingunits: 174659
usedunits: 5341
usedpercentage: 2
unittype: seconds
unlimited: true
scaledusedpercentage: 35
options: []
outofbundle:
usedunits: 0
unittype: EUR
paused: false
mobileinternetonly: false
- mobile: ''
sim: ''
pin: ''
puk: ''
activationstate: active
included:
data:
startunits: 300
start: '300'
remainingunits: 291.98
remaining: 291,98
usedunits: 8.02
used: 8,02
usedpercentage: 2
unittype: GB
unlimited: true
options: []
outofbundle:
usedunits: 0
unittype: EUR
paused: false
mobileinternetonly: true
aggregatedusage:
included:
data:
startunits: 300
start: '300'
remainingunits: 269.67
remaining: 269,67
usedunits: 30.33
used: 30,33
usedpercentage: 10
unittype: GB
unlimited: true
scaledusedpercentage: 10
outofbundle:
usedunits: 0
unittype: EUR
sharedusage:
outofbundle:
usedunits: 0
unittype: EUR
included:
data:
startunits: 300
start: '300'
remainingunits: 269.7
remaining: 269,7
usedunits: 30.3
used: 30,3
usedpercentage: 10
unittype: GB
unlimited: true
options: []
freeride:
active: false
totalusage:
included:
data:
startunits: 300
start: '300'
remainingunits: 269.7
remaining: 269,7
usedunits: 30.3
used: 30,3
usedpercentage: 10
unittype: GB

**Comment by myTselection** [comment]
would you be able to share this as a file or in json format? I need to be able fetch the right fields out of it...

**Comment by Nasimovy** [comment]
[mobile.txt](https://github.com/myTselection/telenet_telemeter/files/10464893/mobile.txt)


like this?

**Comment by myTselection** [comment]
perfect, thanks. I'll probably look into the addition of mobile usage sensors this evening.

**Comment by myTselection** [comment]
I've created a new branch 'mobile' with only sensor.py changed. 
but since I have no Telenet mobile, I can't test any of it decently.
So if anyone would be willing to replace sensor.py within folder custom_components\telenet_telemeter and restart HA.
and share logs of it.
if you'd prefer not to share full logs in here, you may share it by mail too on mytselection [@] gmail.com

**Comment by Nasimovy** [comment]
`mobilemeter data: {'mobileusage': [{'label': 'O1', 'specurl': 'https://api.prd.telenet.be/omapi/public/product/42797', 'identifier': 'O1_46172164', 'nextbillingdate': '2023-01-26T00:00:00.0+01:00', 'lastupdated': '2023-01-21T10:50:01.7+01:00', 'address': {'street': '', 'postalcode': '', 'municipality': '', 'country': '', 'housenr': '', 'addressid': ''}, 'unassigned': {'mobilesubscriptions': []}, 'profiles': [{'pid': '16517642', 'role': 'manager', 'firstname': '', 'lastname': '', 'nickname': '', 'paused': False, 'mobilesubscriptions': [{'mobile': '', 'sim': '', 'pin': '', 'puk': '', 'activationstate': 'active', 'included': {'data': {'startunits': 300.0, 'start': '300', 'remainingunits': 272.9, 'remaining': '272,90', 'usedunits': 27.1, 'used': '27,10', 'usedpercentage': 9, 'unittype': 'GB', 'unlimited': True}, 'text': {'startunits': 30000.0, 'remainingunits': 29990.0, 'usedunits': 10.0, 'usedpercentage': 0, 'unittype': 'number', 'unlimited': True, 'scaledusedpercentage': 1}, 'voice': {'startunits': 180000, 'remainingunits': 174503, 'usedunits': 5497, 'usedpercentage': 3, 'unittype': 'seconds', 'unlimited': True, 'scaledusedpercentage': 36}}, 'options': [], 'outofbundle': {'usedunits': 0.0, 'unittype': 'EUR'}, 'paused': False, 'mobileinternetonly': False}, {'mobile': '', 'sim': '', 'pin': '', 'puk': '', 'activationstate': 'active', 'included': {'data': {'startunits': 300.0, 'start': '300', 'remainingunits': 290.21, 'remaining': '290,21', 'usedunits': 9.79, 'used': '9,79', 'usedpercentage': 3, 'unittype': 'GB', 'unlimited': True}}, 'options': [], 'outofbundle': {'usedunits': 0.0, 'unittype': 'EUR'}, 'paused': False, 'mobileinternetonly': True}], 'aggregatedusage': {'included': {'data': {'startunits': 300.0, 'start': '300', 'remainingunits': 263.11, 'remaining': '263,11', 'usedunits': 36.89, 'used': '36,89', 'usedpercentage': 12, 'unittype': 'GB', 'unlimited': True, 'scaledusedpercentage': 12}}, 'outofbundle': {'usedunits': 0.0, 'unittype': 'EUR'}}}], 'sharedusage': {'outofbundle': {'usedunits': 0.0, 'unittype': 'EUR'}, 'included': {'data': {'startunits': 300.0, 'start': '300', 'remainingunits': 263.1, 'remaining': '263,1', 'usedunits': 36.9, 'used': '36,9', 'usedpercentage': 12, 'unittype': 'GB', 'unlimited': True}}, 'options': []}, 'freeride': {'active': False}, 'totalusage': {'included': {'data': {'startunits': 300.0, 'start': '300', 'remainingunits': 263.1, 'remaining': '263,1', 'usedunits': 36.9, 'used': '36,9', 'usedpercentage': 12, 'unittype': 'GB'}}}}]}`

**Comment by myTselection** [comment]
ok, but did you get any error's when loading the component? That JSON should get processed during initialisation.
I'll try to mock it further so I can test myself..

**Comment by Nasimovy** [comment]
im redownloading logs, will check in a moment, i will email you the whole logs without the sensitive information

**Comment by Nasimovy** [comment]
2023-01-21 11:57:33.280 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.telenet_telemeter_mobile fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    raise exc
  File "/config/custom_components/telenet_telemeter/sensor.py", line 351, in async_update
    self._product = self._data._mobilemeter.get('product')[0].get('label')

**Comment by Nasimovy** [comment]
but before this i cant find any errors, sorry, i first need to figure out how to get logs from only thhis integration and not the whole home assistant install

**Comment by Nasimovy** [comment]
[telenet log.txt](https://github.com/myTselection/telenet_telemeter/files/10472471/telenet.log.txt)

**Comment by Nasimovy** [comment]
Logger: homeassistant.helpers.entity
Source: custom_components/telenet_telemeter/sensor.py:351
Integration: Telenet Telemeter ([documentation](https://github.com/myTselection/telenet_telemeter), [issues](https://github.com/myTselection/telenet_telemeter/issues))
First occurred: 4:47:47 PM (1 occurrences)
Last logged: 4:47:47 PM

Update for sensor.telenet_telemeter_mobile fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    raise exc
  File "/config/custom_components/telenet_telemeter/sensor.py", line 351, in async_update
    self._product = self._data._mobilemeter.get('product')[0].get('label')
TypeError: 'NoneType' object is not subscriptable

**Comment by myTselection** [comment]
nevermind, I have mocked the data based on your input and fixed several bugs. new sensor.py is expected to work more or less

**Comment by myTselection** [comment]
i'll merge the branch back into the main and make a new release

**Comment by myTselection** [comment]
I expect the main part for mobile usage sensors is now stable since r0.5.0. If anything would still be lacking, a new separate issue can be created
