### ISSUE TITLE
total volume and included volume seem to large to make sense

### ISSUE THREAD

**Issue by Nasimovy** [myTselection/telenet_telemeter#7]
I have the ONE subscription

according to telenet if my onpeak usage goes above 3TB i will be restricted
https://www2.telenet.be/content/www-telenet-be/nl/klantenservice/wat-is-telenet-netwerkbeheer.html

according to the collected date this is many times higher

so to calculate the percentage an other value needs to be used at this moment it says 0 percent while it should be approx 0.7 percent

Last update
January 13, 2023 at 8:31:20 AM
Used percentage
0
Included volume
10.485.759.959.105.536
Extended volume
0
Total volume
9.999.999.961
Wifree usage
0
Includedvolume usage
—
Extendedvolume usage
—
Peak usage
21.189.694
Offpeak usage
11.864.558
Period start
December 26, 2022 at 12:00:00 AM
Period end
January 25, 2023 at 12:00:00 AM
Period days left
13
Period used percentage
57

**Comment by myTselection** [comment]
I have a round on the total percentage used, so 0,7 becomes 0. Will try if extra decimals can be added.

**Comment by Nasimovy** [comment]
round above 0,5 will result in 1 no?

and the value total volume is like 9,5 TB

so i dont know really

**Comment by myTselection** [comment]
will add for now a round on two decimals, will see if that helps.
Not sure why there is such a large 'included_volume' value of 10485759959105536. This leads to the large total volume of 9999999961 GB.

**Comment by Nasimovy** [comment]
the issue is still present now i just get 0,0%

i think telenet put such a large volume because its an ''unlimited'' package but after 3TB it will be throttled.
in the product spec https://api.prd.telenet.be/omapi/public/product/43602
they have some info about it
service_category_limit":{"unit":"GB","value":"3072"}

**Comment by myTselection** [comment]
Is this the case for all subscriptions having a distinction between peak and offpeak usage? 
I don't see any info related to the service_category_limit in the current webservices used, but if always applicable, I could hard code this limit and align the % usage based on this... Or I can ask user input on their throttle limit during setup of the integration.

**Comment by myTselection** [comment]
nevermind, I read the details on https://www2.telenet.be/content/www-telenet-be/nl/klantenservice/wat-is-telenet-netwerkbeheer.html
I'll further look into this

**Comment by Nasimovy** [comment]
According to the information i can find on the first url https://www2.telenet.be/content/www-telenet-be/nl/klantenservice/wat-is-telenet-netwerkbeheer.html

There are some packages that have a limit of 750gb peak usage and the rest that have a limit of 3tb peak usage

**Comment by Nasimovy** [comment]
> the issue is still present now i just get 0,0%
> 
> i think telenet put such a large volume because its an ''unlimited'' package but after 3TB it will be throttled.
> in the product spec https://api.prd.telenet.be/omapi/public/product/43602
> they have some info about it
> service_category_limit":{"unit":"GB","value":"3072"}
> 

This product spec url do you have something that looks the same for your subscription?, Maybe you could fetch the date from that url if that's feasible

**Comment by myTselection** [comment]
indeed :)
was just reading through it too. 
while reading, I realized it might also be interesting to have a separate sensor indicating if peak is currently on or not. Might be useful for usage in other automations, eg to pause some network activity till peak is off. Will see if I can include these details per product type and base the max peak volume based on the product type too.

**Comment by myTselection** [comment]
> 

true, didn't realize the relation with the product ID which I do get from current webservice feedback. thanks, will take it up soon...
